#!/bin/bash
if [ ! -e "./qualification" ]
then
  echo "Please run this script from the BSBM root directory"
  exit 1
fi
CP=.
SEP=':'
if [ "$(uname)" = "Cygwin" ]; then SEP=';'; fi
for jar in lib/*.jar
do
  if [ ! -e "$jar" ]; then continue; fi
  CP="$CP$SEP$jar"
done
exec java -cp "$CP" -Xmx256M benchmark.qualification.Qualification "$@"
